<template>
  <section v-if="invitationToken" class="login-shell">
    <el-card class="login-card" v-loading="loading">
      <p class="brand">PEANUT ADMIN</p>
      <template v-if="invitation">
        <h1>接受 Tenant Owner 邀请</h1>
        <p class="muted">{{ invitation.tenant_name }} · {{ invitation.display_name }}（{{ invitation.email_hint }}）</p>
        <el-alert :title="`邀请有效期至 ${invitation.expires_at}`" type="info" :closable="false" />
        <el-form v-if="invitation.requires_password" label-position="top" @submit.prevent="acceptInvitation">
          <el-form-item label="设置账户密码"><el-input v-model="acceptPassword" type="password" show-password autocomplete="new-password" /></el-form-item>
          <el-button native-type="submit" type="primary" :loading="loading" class="wide">接受邀请</el-button>
        </el-form>
        <el-button v-else type="primary" :loading="loading" class="wide" @click="acceptInvitation">接受邀请</el-button>
      </template>
      <el-result v-else-if="error" icon="error" title="邀请不可用" :sub-title="error"><template #extra><el-button @click="clearInvitation">返回平台登录</el-button></template></el-result>
    </el-card>
  </section>
  <section v-else-if="!authenticated" class="login-shell"><el-card class="login-card"><p class="brand">PEANUT ADMIN</p><h1>实例运营平台</h1><p class="muted">PlatformOperator 与 Tenant 管理员身份隔离。</p><el-form @submit.prevent="login"><el-form-item><el-input v-model="credentials.email" placeholder="平台账号邮箱" autocomplete="username" /></el-form-item><el-form-item><el-input v-model="credentials.password" type="password" show-password placeholder="密码" autocomplete="current-password" /></el-form-item><el-alert v-if="error" :title="error" type="error" :closable="false" /><el-button native-type="submit" type="primary" :loading="loading" class="wide">登录平台</el-button></el-form></el-card></section>
  <el-container v-else class="app-shell"><el-aside width="224px"><div class="logo">PEANUT <b>PLATFORM</b></div><el-menu :default-active="view" @select="selectView"><el-menu-item index="overview">概览</el-menu-item><el-menu-item index="tenants">Tenant 与生命周期</el-menu-item><el-menu-item index="owners">Owner 邀请</el-menu-item><el-menu-item index="endpoints">入口域名与客户端</el-menu-item><el-menu-item index="modules">Module 目录</el-menu-item><el-menu-item index="operators">PlatformOperator</el-menu-item><el-menu-item index="roles">平台角色与权限</el-menu-item><el-menu-item index="audit">平台审计</el-menu-item></el-menu></el-aside><el-container><el-header><div><b>{{ title }}</b><span class="muted">实例控制面</span></div><div><el-button text :loading="loading" @click="loadView">刷新</el-button><el-button text @click="logout">退出登录</el-button></div></el-header><el-main><el-alert v-if="error" :title="error" type="error" show-icon @close="error = ''" />
    <template v-if="view === 'overview'"><div class="metric-grid"><el-card><span>Tenant 总数</span><strong>{{ tenants.length }}</strong></el-card><el-card><span>运行中 Tenant</span><strong>{{ activeCount }}</strong></el-card><el-card><span>当前 Tenant 邀请</span><strong>{{ invitations.length }}</strong></el-card><el-card><span>平台操作员</span><strong>{{ operators.length }}</strong></el-card></div><el-card><template #header>实例状态</template><el-descriptions :column="2"><el-descriptions-item label="控制面">PlatformOperator 独立会话</el-descriptions-item><el-descriptions-item label="当前 Tenant">{{ selectedTenant?.display_name || '尚未选择' }}</el-descriptions-item><el-descriptions-item label="Owner">{{ owner?.display_name || '尚未读取' }}</el-descriptions-item><el-descriptions-item label="入口绑定">{{ bindings.length }} 条</el-descriptions-item></el-descriptions></el-card></template>
    <template v-else-if="view === 'tenants'"><div class="toolbar"><el-button type="primary" @click="provisionDialog = true">新建 Tenant</el-button></div><el-table v-loading="loading" :data="tenants" row-key="id" empty-text="暂无 Tenant"><el-table-column prop="code" label="Tenant 编码" /><el-table-column prop="display_name" label="名称" /><el-table-column prop="status" label="状态"><template #default="{ row }"><el-tag :type="statusType(row.status)">{{ row.status }}</el-tag></template></el-table-column><el-table-column prop="revision" label="版本" width="90" /><el-table-column label="操作" width="300"><template #default="{ row }"><el-button link type="primary" @click="showTenant(row)">详情</el-button><el-button v-if="row.status !== 'active' && row.status !== 'closed'" link type="success" @click="changeTenant(row, 'activate')">启用</el-button><el-button v-if="row.status === 'active'" link type="warning" @click="changeTenant(row, 'suspend')">暂停</el-button><el-button v-if="row.status !== 'closed'" link type="danger" @click="changeTenant(row, 'close')">关闭</el-button></template></el-table-column></el-table></template>
    <template v-else-if="view === 'owners'"><tenant-picker /><div class="two-col"><el-card><template #header>发起 Owner 邀请</template><el-form label-position="top" @submit.prevent="sendInvitation"><el-form-item label="Owner 邮箱"><el-input v-model="inviteForm.owner_email" /></el-form-item><el-form-item label="Owner 显示名"><el-input v-model="inviteForm.owner_display_name" /></el-form-item><el-form-item label="有效期（小时）"><el-input-number v-model="inviteForm.expires_in_hours" :min="1" :max="720" /></el-form-item><el-button native-type="submit" type="primary" :loading="loading" :disabled="!selectedTenant">发送邀请</el-button></el-form></el-card><el-card><template #header>当前 Owner</template><el-descriptions v-if="owner" :column="1"><el-descriptions-item label="姓名">{{ owner.display_name }}</el-descriptions-item><el-descriptions-item label="邮箱">{{ owner.email || '未登记' }}</el-descriptions-item><el-descriptions-item label="角色">{{ owner.role_key }}</el-descriptions-item></el-descriptions><el-empty v-else description="尚未找到 Owner" /></el-card></div><el-table v-loading="loading" :data="invitations" empty-text="暂无邀请"><el-table-column prop="email" label="邮箱"/><el-table-column prop="display_name" label="显示名"/><el-table-column prop="status" label="状态"/><el-table-column prop="delivery_status" label="投递"/><el-table-column prop="expires_at" label="过期时间"/><el-table-column label="操作" width="160"><template #default="{ row }"><el-button v-if="row.status === 'pending'" link type="primary" @click="resendInvitation(row)">重发</el-button><el-button v-if="row.status === 'pending'" link type="danger" @click="revokeInvitation(row)">撤销</el-button></template></el-table-column></el-table></template>
    <template v-else-if="view === 'endpoints'"><tenant-picker /><div class="two-col"><el-card><template #header>启用入口绑定</template><el-form label-position="top" @submit.prevent="enableBinding"><el-form-item label="域名"><el-input v-model="bindingForm.host" placeholder="admin.example.com" /></el-form-item><el-form-item label="客户端"><el-select v-model="bindingForm.client_key" class="full"><el-option label="管理端 Web" value="admin-web"/><el-option label="会员 API" value="member-api"/></el-select></el-form-item><el-form-item label="变更原因"><el-input v-model="bindingForm.change_reason" /></el-form-item><el-button native-type="submit" type="primary" :disabled="!selectedTenant" :loading="loading">启用绑定</el-button></el-form></el-card><el-card><template #header>绑定规则</template><p class="muted">一个域名和客户端只能绑定一个有效 Tenant。停用操作会立即撤销该入口识别。</p></el-card></div><el-table v-loading="loading" :data="bindings" empty-text="暂无入口绑定"><el-table-column prop="host" label="域名"/><el-table-column prop="tenant_name" label="Tenant"/><el-table-column prop="client_key" label="客户端"/><el-table-column prop="status" label="状态"/><el-table-column label="操作" width="120"><template #default="{ row }"><el-button v-if="row.status === 'active'" link type="danger" @click="disableBinding(row)">停用</el-button></template></el-table-column></el-table></template>
    <template v-else-if="view === 'modules'"><tenant-picker /><el-table v-loading="loading" :data="modules" empty-text="当前 Tenant 没有 Module 状态"><el-table-column prop="module_key" label="Module"/><el-table-column prop="status" label="状态"/><el-table-column prop="source" label="来源"/><el-table-column prop="config_revision" label="版本"/><el-table-column prop="disabled_reason" label="停用原因"/><el-table-column label="操作" width="140"><template #default="{ row }"><el-button v-if="row.status === 'enabled'" link type="danger" @click="changeModule(row, false)">停用</el-button><el-button v-else link type="success" @click="changeModule(row, true)">启用</el-button></template></el-table-column></el-table></template>
    <template v-else-if="view === 'operators'"><div class="two-col"><el-card><template #header>创建 PlatformOperator</template><el-form label-position="top" @submit.prevent="createOperator"><el-form-item label="邮箱"><el-input v-model="operatorForm.email" /></el-form-item><el-form-item label="显示名"><el-input v-model="operatorForm.display_name" /></el-form-item><el-form-item label="初始密码（已有账户可留空）"><el-input v-model="operatorForm.initial_password" type="password" show-password /></el-form-item><el-button native-type="submit" type="primary" :loading="loading">创建操作员</el-button></el-form></el-card><el-card><template #header>角色分配</template><p class="muted">在下表操作中调整操作员角色；变更会使其下一次会话按新权限生效。</p></el-card></div><el-table v-loading="loading" :data="operators" empty-text="暂无 PlatformOperator"><el-table-column prop="display_name" label="显示名"/><el-table-column prop="email" label="邮箱"/><el-table-column prop="status" label="状态"/><el-table-column label="角色"><template #default="{ row }">{{ row.role_keys.join(', ') || '无' }}</template></el-table-column><el-table-column label="操作" width="310"><template #default="{ row }"><el-button link @click="editOperator(row)">编辑</el-button><el-button link type="primary" @click="assignOperatorRoles(row)">角色</el-button><el-button v-if="row.status !== 'active' && row.status !== 'closed'" link type="success" @click="transitionOperator(row, 'activate')">启用</el-button><el-button v-if="row.status === 'active'" link type="warning" @click="transitionOperator(row, 'suspend')">暂停</el-button><el-button v-if="row.status !== 'closed'" link type="danger" @click="transitionOperator(row, 'close')">关闭</el-button></template></el-table-column></el-table></template>
    <template v-else-if="view === 'roles'"><div class="two-col"><el-card><template #header>创建平台角色</template><el-form label-position="top" @submit.prevent="createRole"><el-form-item label="角色键"><el-input v-model="roleForm.key" placeholder="platform.example.manage" /></el-form-item><el-form-item label="名称"><el-input v-model="roleForm.name" /></el-form-item><el-form-item label="说明"><el-input v-model="roleForm.description" type="textarea" /></el-form-item><el-button native-type="submit" type="primary" :loading="loading">创建角色</el-button></el-form></el-card><el-card><template #header>权限目录{{ permissionRole ? `：${permissionRole.name}` : '' }}</template><el-scrollbar height="220px"><el-checkbox-group v-model="permissionSelection"><el-checkbox v-for="permission in permissions" :key="permission.key" :label="permission.key">{{ permission.name }}（{{ permission.key }}）</el-checkbox></el-checkbox-group></el-scrollbar><el-button type="primary" :disabled="!permissionRole" :loading="loading" @click="savePermissions">保存当前角色权限</el-button></el-card></div><el-table v-loading="loading" :data="roles" empty-text="暂无平台角色"><el-table-column prop="key" label="角色键"/><el-table-column prop="name" label="名称"/><el-table-column prop="status" label="状态"/><el-table-column label="权限"><template #default="{ row }">{{ row.permission_count }}</template></el-table-column><el-table-column label="操作" width="250"><template #default="{ row }"><el-button link @click="editRole(row)">编辑</el-button><el-button link type="primary" @click="editPermissions(row)">编辑权限</el-button><el-button v-if="!row.is_builtin && row.status === 'active'" link type="danger" @click="archiveRole(row)">归档</el-button></template></el-table-column></el-table></template>
    <template v-else-if="view === 'audit'"><el-table v-loading="loading" :data="audits" empty-text="暂无平台审计事件"><el-table-column prop="occurred_at" label="时间" width="180"/><el-table-column prop="event_type" label="事件类型"/><el-table-column prop="action" label="操作"/><el-table-column prop="outcome" label="结果"/><el-table-column prop="target_type" label="目标"/><el-table-column prop="target_id" label="目标 ID"/><el-table-column prop="request_id" label="请求 ID"/></el-table></template>
  </el-main></el-container></el-container>
  <el-dialog v-model="provisionDialog" title="新建 Tenant" width="520px"><el-form label-position="top"><el-form-item label="Tenant 编码"><el-input v-model="provision.tenant_code" /></el-form-item><el-form-item label="Tenant 名称"><el-input v-model="provision.tenant_name" /></el-form-item><el-form-item label="Owner 邮箱"><el-input v-model="provision.owner_email" /></el-form-item><el-form-item label="Owner 显示名"><el-input v-model="provision.owner_display_name" /></el-form-item><el-form-item label="邀请有效期（小时）"><el-input-number v-model="provision.expires_in_hours" :min="1" :max="720" /></el-form-item></el-form><template #footer><el-button @click="provisionDialog=false">取消</el-button><el-button type="primary" :loading="loading" @click="createTenant">创建并发送邀请</el-button></template></el-dialog>
</template>

<script setup lang="ts">
import { computed, defineComponent, h, onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox, ElOption, ElSelect } from 'element-plus';
import { api, type AuditEvent, type EntryBinding, type Invitation, type InvitationInspection, type ModuleState, type Operator, type Permission, type PlatformRole, type Tenant, type TenantOwner } from './api/platform';

const tokenFromUrl = new URLSearchParams(window.location.search).get('invitation');
const invitationToken = ref(tokenFromUrl || ''); const invitation = ref<InvitationInspection | null>(null); const acceptPassword = ref('');
const authenticated = ref(!!localStorage.getItem('peanut-platform-token')); const loading = ref(false); const error = ref(''); const view = ref('overview'); const tenants = ref<Tenant[]>([]); const invitations = ref<Invitation[]>([]); const bindings = ref<EntryBinding[]>([]); const modules = ref<ModuleState[]>([]); const operators = ref<Operator[]>([]); const roles = ref<PlatformRole[]>([]); const permissions = ref<Permission[]>([]); const audits = ref<AuditEvent[]>([]); const owner = ref<TenantOwner | null>(null); const selectedTenantId = ref<number | null>(null); const provisionDialog = ref(false); const permissionSelection = ref<string[]>([]); const permissionRole = ref<PlatformRole | null>(null);
const credentials = reactive({ email: '', password: '' }); const provision = reactive({ tenant_code: '', tenant_name: '', owner_email: '', owner_display_name: '', expires_in_hours: 72 }); const inviteForm = reactive({ owner_email: '', owner_display_name: '', expires_in_hours: 72 }); const bindingForm = reactive({ host: '', client_key: 'admin-web', change_reason: '' }); const operatorForm = reactive({ email: '', display_name: '', initial_password: '' }); const roleForm = reactive({ key: '', name: '', description: '' });
const labels: Record<string, string> = { overview: '概览', tenants: 'Tenant 与生命周期', owners: 'Owner 邀请管理', endpoints: '入口域名与客户端', modules: 'Module 目录与 Tenant 状态', operators: 'PlatformOperator', roles: 'PlatformRole 与权限', audit: '平台审计' }; const title = computed(() => labels[view.value]); const activeCount = computed(() => tenants.value.filter((tenant) => tenant.status === 'active').length); const selectedTenant = computed(() => tenants.value.find((tenant) => tenant.id === selectedTenantId.value));
const TenantPicker = defineComponent({ setup: () => () => h('div', { class: 'toolbar' }, [h('span', { class: 'muted' }, '操作 Tenant'), h(ElSelect, { modelValue: selectedTenantId.value, 'onUpdate:modelValue': (id: number) => { selectedTenantId.value = id; void loadView(); }, placeholder: '选择 Tenant', style: 'width: 280px' }, () => tenants.value.map((tenant) => h(ElOption, { key: tenant.id, label: `${tenant.display_name} (${tenant.code})`, value: tenant.id })))]) });
function statusType(status: string) { return status === 'active' || status === 'enabled' ? 'success' : status === 'suspended' ? 'warning' : status === 'closed' || status === 'disabled' ? 'danger' : 'info'; }
function message(cause: unknown) { return cause instanceof Error ? cause.message : '请求失败，请稍后重试'; }
async function run(action: () => Promise<unknown>, success: string) { loading.value = true; error.value = ''; try { await action(); ElMessage.success(success); await loadView(); } catch (cause) { error.value = message(cause); } finally { loading.value = false; } }
async function loadTenants() { const result = await api.tenants(); tenants.value = result.lists; if (!selectedTenantId.value && tenants.value[0]) selectedTenantId.value = tenants.value[0].id; }
async function loadView() { loading.value = true; error.value = ''; try { await loadTenants(); const id = selectedTenantId.value; if (view.value === 'overview') { [operators.value, bindings.value] = [(await api.operators()).lists, await api.entryBindings(id || undefined)]; if (id) { invitations.value = (await api.invitations(id)).lists; try { owner.value = await api.tenantOwner(id); } catch { owner.value = null; } } } else if (view.value === 'owners' && id) { [invitations.value, owner.value] = [(await api.invitations(id)).lists, await api.tenantOwner(id).catch(() => null)]; } else if (view.value === 'endpoints') bindings.value = await api.entryBindings(id || undefined); else if (view.value === 'modules' && id) modules.value = (await api.moduleStates(id)).lists; else if (view.value === 'operators') { [operators.value, roles.value] = [(await api.operators()).lists, (await api.roles()).lists]; } else if (view.value === 'roles') { [roles.value, permissions.value] = [(await api.roles()).lists, (await api.permissions()).lists]; } else if (view.value === 'audit') audits.value = (await api.audit()).lists; } catch (cause) { error.value = message(cause); } finally { loading.value = false; } }
async function selectView(next: string) { view.value = next; await loadView(); }
async function login() { await run(async () => { await api.login(credentials.email.trim(), credentials.password); authenticated.value = true; credentials.password = ''; }, '登录成功'); }
async function logout() { await api.logout(); authenticated.value = false; tenants.value = []; view.value = 'overview'; }
async function inspectInvitation() { if (!invitationToken.value) return; loading.value = true; error.value = ''; try { invitation.value = await api.inspectInvitation(invitationToken.value); } catch (cause) { error.value = message(cause); } finally { loading.value = false; } }
async function acceptInvitation() { loading.value = true; error.value = ''; try { await api.acceptInvitation(invitationToken.value, acceptPassword.value); invitation.value = null; invitationToken.value = ''; window.history.replaceState({}, '', window.location.pathname); ElMessage.success('邀请已接受，请使用账户登录 Tenant'); } catch (cause) { error.value = message(cause); } finally { loading.value = false; } }
function clearInvitation() { invitationToken.value = ''; window.history.replaceState({}, '', window.location.pathname); error.value = ''; }
async function createTenant() { await run(async () => { await api.provision({ ...provision }); provisionDialog.value = false; Object.assign(provision, { tenant_code: '', tenant_name: '', owner_email: '', owner_display_name: '', expires_in_hours: 72 }); }, 'Tenant 已创建，Owner 邀请已发出'); }
async function changeTenant(tenant: Tenant, action: 'activate' | 'suspend' | 'close') { try { await ElMessageBox.confirm(`确认${action} ${tenant.display_name}？`, '确认生命周期变更', { type: 'warning' }); const result = await ElMessageBox.prompt('填写变更原因', '变更原因', { inputPattern: /\S+/, inputErrorMessage: '必须填写原因' }); await run(() => api.transition(action, tenant, result.value), 'Tenant 状态已更新'); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
async function showTenant(tenant: Tenant) { loading.value = true; try { const detail = await api.tenantDetail(tenant.id); await ElMessageBox.alert(`<pre>${escapeHtml(JSON.stringify(detail, null, 2))}</pre>`, `${tenant.display_name} 详情`, { dangerouslyUseHTMLString: true }); } catch (cause) { error.value = message(cause); } finally { loading.value = false; } }
function escapeHtml(value: string) { return value.replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char] || char)); }
async function sendInvitation() { if (!selectedTenantId.value) return; await run(() => api.inviteOwner({ tenant_id: selectedTenantId.value!, ...inviteForm }), 'Owner 邀请已发出'); }
async function resendInvitation(item: Invitation) { await run(() => api.resendInvitation(item.id), '邀请已重新发送'); }
async function revokeInvitation(item: Invitation) { try { await ElMessageBox.confirm(`撤销 ${item.email} 的邀请？`, '确认撤销', { type: 'warning' }); await run(() => api.revokeInvitation(item.id), '邀请已撤销'); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
async function enableBinding() { if (!selectedTenantId.value) return; await run(() => api.enableEntryBinding({ tenant_id: selectedTenantId.value!, ...bindingForm }), '入口绑定已启用'); }
async function disableBinding(item: EntryBinding) { try { const result = await ElMessageBox.prompt('填写停用原因', `停用 ${item.host}`, { inputPattern: /\S+/, inputErrorMessage: '必须填写原因' }); await run(() => api.disableEntryBinding(item.id, result.value), '入口绑定已停用'); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
async function changeModule(item: ModuleState, enabled: boolean) { if (!selectedTenantId.value) return; try { const result = await ElMessageBox.prompt('填写变更原因', `${enabled ? '启用' : '停用'} ${item.module_key}`, { inputPattern: /\S+/, inputErrorMessage: '必须填写原因' }); await run(() => api.changeModule(enabled, selectedTenantId.value!, item.module_key, result.value), `Module 已${enabled ? '启用' : '停用'}`); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
async function createOperator() { await run(async () => { await api.createOperator({ ...operatorForm }); Object.assign(operatorForm, { email: '', display_name: '', initial_password: '' }); }, 'PlatformOperator 已创建'); }
async function editOperator(item: Operator) { try { const name = await ElMessageBox.prompt('显示名', `编辑 ${item.display_name}`, { inputValue: item.display_name, inputPattern: /\S+/, inputErrorMessage: '必须填写显示名' }); const reason = await ElMessageBox.prompt('变更原因', '变更原因', { inputPattern: /\S+/, inputErrorMessage: '必须填写原因' }); await run(() => api.updateOperator(item, name.value, reason.value), '操作员已更新'); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
async function assignOperatorRoles(item: Operator) { try { const result = await ElMessageBox.prompt(`输入角色 ID，多个用逗号分隔。可选：${roles.value.map((role) => `${role.id}:${role.name}`).join('，')}`, '分配角色', { inputValue: '', inputPattern: /^\d+(\s*,\s*\d+)*$/, inputErrorMessage: '请输入一个或多个角色 ID' }); const reason = await ElMessageBox.prompt('变更原因', '变更原因', { inputPattern: /\S+/, inputErrorMessage: '必须填写原因' }); await run(() => api.replaceOperatorRoles(item, result.value.split(',').map((id) => Number(id.trim())), reason.value), '角色分配已更新'); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
async function transitionOperator(item: Operator, action: 'activate' | 'suspend' | 'close') { try { const reason = await ElMessageBox.prompt('变更原因', `${action} ${item.display_name}`, { inputPattern: /\S+/, inputErrorMessage: '必须填写原因' }); await run(() => api.transitionOperator(action, item, reason.value), '操作员状态已更新'); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
async function createRole() { await run(async () => { await api.createRole({ ...roleForm }); Object.assign(roleForm, { key: '', name: '', description: '' }); }, '平台角色已创建'); }
async function editRole(item: PlatformRole) { try { const name = await ElMessageBox.prompt('角色名称', `编辑 ${item.key}`, { inputValue: item.name, inputPattern: /\S+/, inputErrorMessage: '必须填写名称' }); const description = await ElMessageBox.prompt('说明', '角色说明', { inputValue: item.description || '' }); const reason = await ElMessageBox.prompt('变更原因', '变更原因', { inputPattern: /\S+/, inputErrorMessage: '必须填写原因' }); await run(() => api.updateRole(item, name.value, description.value, reason.value), '平台角色已更新'); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
function editPermissions(item: PlatformRole) { permissionRole.value = item; permissionSelection.value = [...item.permission_keys]; }
async function savePermissions() { if (!permissionRole.value) return; try { const reason = await ElMessageBox.prompt('变更原因', `保存 ${permissionRole.value.name} 的权限`, { inputPattern: /\S+/, inputErrorMessage: '必须填写原因' }); await run(() => api.replaceRolePermissions(permissionRole.value!, permissionSelection.value, reason.value), '角色权限已更新'); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
async function archiveRole(item: PlatformRole) { try { await ElMessageBox.confirm(`归档 ${item.name}？`, '确认归档', { type: 'warning' }); const reason = await ElMessageBox.prompt('变更原因', '变更原因', { inputPattern: /\S+/, inputErrorMessage: '必须填写原因' }); await run(() => api.archiveRole(item, reason.value), '平台角色已归档'); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
onMounted(async () => { if (invitationToken.value) await inspectInvitation(); else if (authenticated.value) await loadView(); });
</script>
