<template>
  <section v-if="invitationToken" class="login-shell">
    <el-card class="login-card" v-loading="loading">
      <p class="brand">PEANUT ADMIN</p>
      <template v-if="invitation">
        <h1>接受租户所有者邀请</h1>
        <p class="muted">{{ invitation.tenant_name }} · {{ invitation.display_name }}（{{ invitation.email_hint }}）</p>
        <el-alert :title="`邀请有效期至 ${invitation.expires_at}`" type="info" :closable="false" />
        <el-form v-if="invitation.requires_password" label-position="top" @submit.prevent="acceptInvitation">
          <el-form-item label="设置账户密码"><el-input v-model="acceptPassword" type="password" show-password autocomplete="new-password" /></el-form-item>
          <el-button native-type="submit" type="primary" :loading="loading" class="wide">接受邀请</el-button>
        </el-form>
        <el-button v-else type="primary" :loading="loading" class="wide" @click="acceptInvitation">接受邀请</el-button>
      </template>
      <el-result v-else-if="error" icon="error" title="邀请不可用" :sub-title="error"><template #extra><el-button @click="goToTenantLogin">前往租户管理端登录</el-button></template></el-result>
    </el-card>
  </section>
  <section v-else-if="!authenticated" class="login-shell"><el-card class="login-card"><p class="brand">PEANUT ADMIN</p><h1>实例平台管理</h1><p class="muted">实例平台操作员使用独立平台会话；平台身份不授予租户业务权限。</p><el-form @submit.prevent="login"><el-form-item><el-input v-model="credentials.email" placeholder="实例平台操作员邮箱" autocomplete="username" /></el-form-item><el-form-item><el-input v-model="credentials.password" type="password" show-password placeholder="密码" autocomplete="current-password" /></el-form-item><el-alert v-if="error" :title="error" type="error" :closable="false" /><el-button native-type="submit" type="primary" :loading="loading" class="wide">登录实例平台</el-button></el-form></el-card></section>
  <el-container v-else class="app-shell"><el-aside width="224px"><div class="logo">PEANUT <b>平台</b></div><el-menu :default-active="view" @select="selectView"><el-menu-item index="overview">概览</el-menu-item><el-menu-item index="tenants">租户与生命周期</el-menu-item><el-menu-item index="owners">租户所有者邀请</el-menu-item><el-menu-item index="endpoints">入口域名与客户端</el-menu-item><el-menu-item index="modules">模块目录</el-menu-item><el-menu-item index="operators">实例平台操作员</el-menu-item><el-menu-item index="roles">平台角色与权限</el-menu-item><el-menu-item index="audit">平台审计</el-menu-item></el-menu></el-aside><el-container><el-header><div><b>{{ title }}</b><span class="muted">实例平台控制面</span></div><div><el-button text :loading="loading" @click="loadView">刷新</el-button><el-button text @click="logout">退出登录</el-button></div></el-header><el-main><el-alert v-if="error" :title="error" type="error" show-icon @close="error = ''" />
    <template v-if="view === 'overview'"><div class="metric-grid"><el-card><span>租户总数</span><strong>{{ tenants.length }}</strong></el-card><el-card><span>运行中租户</span><strong>{{ activeCount }}</strong></el-card><el-card><span>实例平台操作员</span><strong>{{ operators.length }}</strong></el-card></div><el-card><template #header>实例状态</template><el-descriptions :column="2"><el-descriptions-item label="控制面">实例平台操作员独立会话</el-descriptions-item><el-descriptions-item label="治理范围">仅管理本实例租户，不进入租户业务会话</el-descriptions-item></el-descriptions></el-card></template>
    <template v-else-if="view === 'tenants'"><div class="toolbar"><el-button type="primary" @click="provisionDialog = true">新建租户</el-button></div><el-table v-loading="loading" :data="tenants" row-key="id" empty-text="暂无租户"><el-table-column prop="code" label="租户编码" /><el-table-column prop="display_name" label="名称" /><el-table-column prop="status" label="状态"><template #default="{ row }"><el-tag :type="statusType(row.status)">{{ statusLabel(row.status) }}</el-tag></template></el-table-column><el-table-column prop="revision" label="版本" width="90" /><el-table-column label="操作" width="300"><template #default="{ row }"><el-button link type="primary" @click="showTenant(row)">详情</el-button><el-button v-if="row.status !== 'active' && row.status !== 'closed'" link type="success" @click="changeTenant(row, 'activate')">启用</el-button><el-button v-if="row.status === 'active'" link type="warning" @click="changeTenant(row, 'suspend')">暂停</el-button><el-button v-if="row.status !== 'closed'" link type="danger" @click="changeTenant(row, 'close')">关闭</el-button></template></el-table-column></el-table></template>
    <template v-else-if="view === 'owners'"><tenant-picker /><div class="two-col"><el-card><template #header>发起租户所有者邀请</template><el-form label-position="top" @submit.prevent="sendInvitation"><el-form-item label="所有者邮箱"><el-input v-model="inviteForm.owner_email" /></el-form-item><el-form-item label="所有者显示名"><el-input v-model="inviteForm.owner_display_name" /></el-form-item><el-form-item label="有效期（小时）"><el-input-number v-model="inviteForm.expires_in_hours" :min="1" :max="720" /></el-form-item><el-button native-type="submit" type="primary" :loading="loading" :disabled="!targetTenant">发送邀请</el-button></el-form></el-card><el-card><template #header>目标租户所有者</template><el-descriptions v-if="owner" :column="1"><el-descriptions-item label="姓名">{{ owner.display_name }}</el-descriptions-item><el-descriptions-item label="邮箱">{{ owner.email || '未登记' }}</el-descriptions-item><el-descriptions-item label="角色">租户所有者（{{ owner.role_key }}）</el-descriptions-item></el-descriptions><el-empty v-else description="尚未找到租户所有者" /></el-card></div><el-table v-loading="loading" :data="invitations" empty-text="暂无邀请"><el-table-column prop="email" label="邮箱"/><el-table-column prop="display_name" label="显示名"/><el-table-column prop="status" label="状态"><template #default="{ row }">{{ statusLabel(row.status) }}</template></el-table-column><el-table-column prop="delivery_status" label="投递状态"><template #default="{ row }">{{ statusLabel(row.delivery_status) }}</template></el-table-column><el-table-column prop="expires_at" label="过期时间"/><el-table-column label="操作" width="160"><template #default="{ row }"><el-button v-if="row.status === 'pending'" link type="primary" @click="resendInvitation(row)">重发</el-button><el-button v-if="row.status === 'pending'" link type="danger" @click="revokeInvitation(row)">撤销</el-button></template></el-table-column></el-table></template>
    <template v-else-if="view === 'endpoints'"><tenant-picker /><div class="two-col"><el-card><template #header>启用入口绑定</template><el-form label-position="top" @submit.prevent="enableBinding"><el-form-item label="域名"><el-input v-model="bindingForm.host" placeholder="admin.example.com" /></el-form-item><el-form-item label="客户端"><el-select v-model="bindingForm.client_key" class="full"><el-option label="管理端网页" value="admin-web"/><el-option label="会员接口" value="member-api"/></el-select></el-form-item><el-form-item label="变更原因"><el-input v-model="bindingForm.change_reason" /></el-form-item><el-button native-type="submit" type="primary" :disabled="!targetTenant" :loading="loading">启用绑定</el-button></el-form></el-card><el-card><template #header>绑定规则</template><p class="muted">一个域名和客户端只能绑定一个有效租户。停用操作会立即撤销该入口识别。</p></el-card></div><el-table v-loading="loading" :data="bindings" empty-text="暂无入口绑定"><el-table-column prop="host" label="域名"/><el-table-column prop="tenant_name" label="租户"/><el-table-column prop="client_key" label="客户端"><template #default="{ row }">{{ clientLabel(row.client_key) }}</template></el-table-column><el-table-column prop="status" label="状态"><template #default="{ row }">{{ statusLabel(row.status) }}</template></el-table-column><el-table-column label="操作" width="120"><template #default="{ row }"><el-button v-if="row.status === 'active'" link type="danger" @click="disableBinding(row)">停用</el-button></template></el-table-column></el-table></template>
    <template v-else-if="view === 'modules'"><tenant-picker /><el-table v-loading="loading" :data="modules" empty-text="目标租户没有模块状态"><el-table-column prop="module_key" label="模块键"/><el-table-column prop="status" label="状态"><template #default="{ row }">{{ statusLabel(row.status) }}</template></el-table-column><el-table-column prop="source" label="来源"/><el-table-column prop="config_revision" label="版本"/><el-table-column prop="disabled_reason" label="停用原因"/><el-table-column label="操作" width="140"><template #default="{ row }"><el-button v-if="row.status === 'enabled'" link type="danger" @click="changeModule(row, false)">停用</el-button><el-button v-else link type="success" @click="changeModule(row, true)">启用</el-button></template></el-table-column></el-table></template>
    <template v-else-if="view === 'operators'"><div class="two-col"><el-card><template #header>创建平台操作员</template><el-form label-position="top" @submit.prevent="createOperator"><el-form-item label="邮箱"><el-input v-model="operatorForm.email" /></el-form-item><el-form-item label="显示名"><el-input v-model="operatorForm.display_name" /></el-form-item><el-form-item label="初始密码（已有账户可留空）"><el-input v-model="operatorForm.initial_password" type="password" show-password /></el-form-item><el-button native-type="submit" type="primary" :loading="loading">创建操作员</el-button></el-form></el-card><el-card><template #header>角色分配</template><p class="muted">在下表操作中调整操作员角色；变更会使其下一次会话按新权限生效。</p></el-card></div><el-table v-loading="loading" :data="operators" empty-text="暂无平台操作员"><el-table-column prop="display_name" label="显示名"/><el-table-column prop="email" label="邮箱"/><el-table-column prop="status" label="状态"><template #default="{ row }">{{ statusLabel(row.status) }}</template></el-table-column><el-table-column label="角色"><template #default="{ row }">{{ row.role_keys.join(', ') || '无' }}</template></el-table-column><el-table-column label="操作" width="310"><template #default="{ row }"><el-button link @click="editOperator(row)">编辑</el-button><el-button link type="primary" @click="assignOperatorRoles(row)">角色</el-button><el-button v-if="row.status !== 'active' && row.status !== 'closed'" link type="success" @click="transitionOperator(row, 'activate')">启用</el-button><el-button v-if="row.status === 'active'" link type="warning" @click="transitionOperator(row, 'suspend')">暂停</el-button><el-button v-if="row.status !== 'closed'" link type="danger" @click="transitionOperator(row, 'close')">关闭</el-button></template></el-table-column></el-table></template>
    <template v-else-if="view === 'roles'"><div class="two-col"><el-card><template #header>创建平台角色</template><el-form label-position="top" @submit.prevent="createRole"><el-form-item label="角色键"><el-input v-model="roleForm.key" placeholder="platform.example.manage" /></el-form-item><el-form-item label="名称"><el-input v-model="roleForm.name" /></el-form-item><el-form-item label="说明"><el-input v-model="roleForm.description" type="textarea" /></el-form-item><el-button native-type="submit" type="primary" :loading="loading">创建角色</el-button></el-form></el-card><el-card><template #header>权限目录{{ permissionRole ? `：${permissionRole.name}` : '' }}</template><el-scrollbar height="220px"><el-checkbox-group v-model="permissionSelection"><el-checkbox v-for="permission in permissions" :key="permission.key" :label="permission.key">{{ permission.name }}（{{ permission.key }}）</el-checkbox></el-checkbox-group></el-scrollbar><el-button type="primary" :disabled="!permissionRole" :loading="loading" @click="savePermissions">保存当前角色权限</el-button></el-card></div><el-table v-loading="loading" :data="roles" empty-text="暂无平台角色"><el-table-column prop="key" label="角色键"/><el-table-column prop="name" label="名称"/><el-table-column prop="status" label="状态"/><el-table-column label="权限"><template #default="{ row }">{{ row.permission_count }}</template></el-table-column><el-table-column label="操作" width="250"><template #default="{ row }"><el-button link @click="editRole(row)">编辑</el-button><el-button link type="primary" @click="editPermissions(row)">编辑权限</el-button><el-button v-if="!row.is_builtin && row.status === 'active'" link type="danger" @click="archiveRole(row)">归档</el-button></template></el-table-column></el-table></template>
    <template v-else-if="view === 'audit'"><el-table v-loading="loading" :data="audits" empty-text="暂无平台审计事件"><el-table-column prop="occurred_at" label="时间" width="180"/><el-table-column prop="event_type" label="事件类型"/><el-table-column prop="action" label="操作"/><el-table-column prop="outcome" label="结果"/><el-table-column prop="target_type" label="目标"/><el-table-column prop="target_id" label="目标 ID"/><el-table-column prop="request_id" label="请求 ID"/></el-table></template>
  </el-main></el-container></el-container>
  <el-dialog v-model="provisionDialog" title="新建租户" width="520px"><el-form label-position="top"><el-form-item label="租户编码"><el-input v-model="provision.tenant_code" /></el-form-item><el-form-item label="租户名称"><el-input v-model="provision.tenant_name" /></el-form-item><el-form-item label="首位所有者邮箱"><el-input v-model="provision.owner_email" /></el-form-item><el-form-item label="首位所有者显示名"><el-input v-model="provision.owner_display_name" /></el-form-item><el-form-item label="邀请有效期（小时）"><el-input-number v-model="provision.expires_in_hours" :min="1" :max="720" /></el-form-item></el-form><template #footer><el-button @click="provisionDialog=false">取消</el-button><el-button type="primary" :loading="loading" @click="createTenant">创建并发送邀请</el-button></template></el-dialog>
</template>

<script setup lang="ts">
import { computed, defineComponent, h, onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox, ElOption, ElSelect } from 'element-plus';
import { api, type AuditEvent, type EntryBinding, type Invitation, type InvitationInspection, type ModuleState, type Operator, type Permission, type PlatformRole, type Tenant, type TenantOwner } from './api/platform';

const tokenFromUrl = new URLSearchParams(window.location.search).get('invitation');
const invitationToken = ref(tokenFromUrl || ''); const invitation = ref<InvitationInspection | null>(null); const acceptPassword = ref('');
const authenticated = ref(!!localStorage.getItem('peanut-platform-token')); const loading = ref(false); const error = ref(''); const view = ref('overview'); const tenants = ref<Tenant[]>([]); const invitations = ref<Invitation[]>([]); const bindings = ref<EntryBinding[]>([]); const modules = ref<ModuleState[]>([]); const operators = ref<Operator[]>([]); const roles = ref<PlatformRole[]>([]); const permissions = ref<Permission[]>([]); const audits = ref<AuditEvent[]>([]); const owner = ref<TenantOwner | null>(null); const targetTenantId = ref<number | null>(null); const provisionDialog = ref(false); const permissionSelection = ref<string[]>([]); const permissionRole = ref<PlatformRole | null>(null);
const credentials = reactive({ email: '', password: '' }); const provision = reactive({ tenant_code: '', tenant_name: '', owner_email: '', owner_display_name: '', expires_in_hours: 72 }); const inviteForm = reactive({ owner_email: '', owner_display_name: '', expires_in_hours: 72 }); const bindingForm = reactive({ host: '', client_key: 'admin-web', change_reason: '' }); const operatorForm = reactive({ email: '', display_name: '', initial_password: '' }); const roleForm = reactive({ key: '', name: '', description: '' });
const labels: Record<string, string> = { overview: '概览', tenants: '租户与生命周期', owners: '租户所有者邀请管理', endpoints: '入口域名与客户端', modules: '模块目录与租户状态', operators: '实例平台操作员', roles: '平台角色与权限', audit: '平台审计' }; const title = computed(() => labels[view.value]); const activeCount = computed(() => tenants.value.filter((tenant) => tenant.status === 'active').length); const targetTenant = computed(() => tenants.value.find((tenant) => tenant.id === targetTenantId.value));
const TenantPicker = defineComponent({ setup: () => () => h('div', { class: 'toolbar' }, [h('span', { class: 'muted' }, '操作目标租户'), h(ElSelect, { modelValue: targetTenantId.value, 'onUpdate:modelValue': (id: number) => { targetTenantId.value = id; void loadView(); }, placeholder: '选择目标租户', style: 'width: 280px' }, () => tenants.value.map((tenant) => h(ElOption, { key: tenant.id, label: `${tenant.display_name} (${tenant.code})`, value: tenant.id })))]) });
function statusType(status: string) { return status === 'active' || status === 'enabled' ? 'success' : status === 'suspended' ? 'warning' : status === 'closed' || status === 'disabled' ? 'danger' : 'info'; }
function statusLabel(status: string) { return ({ active: '正常', enabled: '已启用', provisioning: '待配置', pending: '待接受', pending_delivery: '待投递', delivered: '已投递', accepted: '已接受', revoked: '已撤销', expired: '已过期', suspended: '已暂停', disabled: '已停用', closed: '已关闭' } as Record<string, string>)[status] || status; }
function clientLabel(client: string) { return ({ 'admin-web': '管理端网页', 'member-api': '会员接口' } as Record<string, string>)[client] || client; }
function message(cause: unknown) { return cause instanceof Error ? cause.message : '请求失败，请稍后重试'; }
async function run(action: () => Promise<unknown>, success: string) { loading.value = true; error.value = ''; try { await action(); ElMessage.success(success); await loadView(); } catch (cause) { error.value = message(cause); } finally { loading.value = false; } }
async function loadTenants() { const result = await api.tenants(); tenants.value = result.lists; if (targetTenantId.value && !targetTenant.value) targetTenantId.value = null; }
async function loadView() { loading.value = true; error.value = ''; try { await loadTenants(); const id = targetTenantId.value; if (view.value === 'overview') operators.value = (await api.operators()).lists; else if (view.value === 'owners') { if (id) [invitations.value, owner.value] = [(await api.invitations(id)).lists, await api.tenantOwner(id).catch(() => null)]; else [invitations.value, owner.value] = [[], null]; } else if (view.value === 'endpoints') bindings.value = id ? await api.entryBindings(id) : []; else if (view.value === 'modules') modules.value = id ? (await api.moduleStates(id)).lists : []; else if (view.value === 'operators') { [operators.value, roles.value] = [(await api.operators()).lists, (await api.roles()).lists]; } else if (view.value === 'roles') { [roles.value, permissions.value] = [(await api.roles()).lists, (await api.permissions()).lists]; } else if (view.value === 'audit') audits.value = (await api.audit()).lists; } catch (cause) { error.value = message(cause); } finally { loading.value = false; } }
async function selectView(next: string) { view.value = next; await loadView(); }
async function login() { await run(async () => { await api.login(credentials.email.trim(), credentials.password); authenticated.value = true; credentials.password = ''; }, '登录成功'); }
async function logout() { await api.logout(); authenticated.value = false; tenants.value = []; targetTenantId.value = null; view.value = 'overview'; }
async function inspectInvitation() { if (!invitationToken.value) return; loading.value = true; error.value = ''; try { invitation.value = await api.inspectInvitation(invitationToken.value); } catch (cause) { error.value = message(cause); } finally { loading.value = false; } }
async function acceptInvitation() { loading.value = true; error.value = ''; try { await api.acceptInvitation(invitationToken.value, acceptPassword.value); invitation.value = null; invitationToken.value = ''; window.history.replaceState({}, '', window.location.pathname); ElMessage.success('邀请已接受，请使用账户登录 Tenant'); } catch (cause) { error.value = message(cause); } finally { loading.value = false; } }
function goToTenantLogin() { window.location.assign('/admin/'); }
async function createTenant() { await run(async () => { await api.provision({ ...provision }); provisionDialog.value = false; Object.assign(provision, { tenant_code: '', tenant_name: '', owner_email: '', owner_display_name: '', expires_in_hours: 72 }); }, '租户已创建，所有者邀请已发出'); }
async function changeTenant(tenant: Tenant, action: 'activate' | 'suspend' | 'close') { const actionLabel = { activate: '启用', suspend: '暂停', close: '关闭' }[action]; try { await ElMessageBox.confirm(`确认${actionLabel} ${tenant.display_name}？`, '确认生命周期变更', { type: 'warning' }); const result = await ElMessageBox.prompt('填写变更原因', '变更原因', { inputPattern: /\S+/, inputErrorMessage: '必须填写原因' }); await run(() => api.transition(action, tenant, result.value), '租户状态已更新'); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
async function showTenant(tenant: Tenant) { loading.value = true; try { const detail = await api.tenantDetail(tenant.id); await ElMessageBox.alert(`<pre>${escapeHtml(JSON.stringify(detail, null, 2))}</pre>`, `${tenant.display_name} 详情`, { dangerouslyUseHTMLString: true }); } catch (cause) { error.value = message(cause); } finally { loading.value = false; } }
function escapeHtml(value: string) { return value.replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char] || char)); }
async function sendInvitation() { if (!targetTenantId.value) return; await run(() => api.inviteOwner({ tenant_id: targetTenantId.value!, ...inviteForm }), '租户所有者邀请已发出'); }
async function resendInvitation(item: Invitation) { await run(() => api.resendInvitation(item.id), '邀请已重新发送'); }
async function revokeInvitation(item: Invitation) { try { await ElMessageBox.confirm(`撤销 ${item.email} 的邀请？`, '确认撤销', { type: 'warning' }); await run(() => api.revokeInvitation(item.id), '邀请已撤销'); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
async function enableBinding() { if (!targetTenantId.value) return; await run(() => api.enableEntryBinding({ tenant_id: targetTenantId.value!, ...bindingForm }), '入口绑定已启用'); }
async function disableBinding(item: EntryBinding) { try { const result = await ElMessageBox.prompt('填写停用原因', `停用 ${item.host}`, { inputPattern: /\S+/, inputErrorMessage: '必须填写原因' }); await run(() => api.disableEntryBinding(item.id, result.value), '入口绑定已停用'); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
async function changeModule(item: ModuleState, enabled: boolean) { if (!targetTenantId.value) return; try { const result = await ElMessageBox.prompt('填写变更原因', `${enabled ? '启用' : '停用'} ${item.module_key}`, { inputPattern: /\S+/, inputErrorMessage: '必须填写原因' }); await run(() => api.changeModule(enabled, targetTenantId.value!, item.module_key, result.value), `模块已${enabled ? '启用' : '停用'}`); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
async function createOperator() { await run(async () => { await api.createOperator({ ...operatorForm }); Object.assign(operatorForm, { email: '', display_name: '', initial_password: '' }); }, '平台操作员已创建'); }
async function editOperator(item: Operator) { try { const name = await ElMessageBox.prompt('显示名', `编辑 ${item.display_name}`, { inputValue: item.display_name, inputPattern: /\S+/, inputErrorMessage: '必须填写显示名' }); const reason = await ElMessageBox.prompt('变更原因', '变更原因', { inputPattern: /\S+/, inputErrorMessage: '必须填写原因' }); await run(() => api.updateOperator(item, name.value, reason.value), '操作员已更新'); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
async function assignOperatorRoles(item: Operator) { try { const result = await ElMessageBox.prompt(`输入角色 ID，多个用逗号分隔。可选：${roles.value.map((role) => `${role.id}:${role.name}`).join('，')}`, '分配角色', { inputValue: '', inputPattern: /^\d+(\s*,\s*\d+)*$/, inputErrorMessage: '请输入一个或多个角色 ID' }); const reason = await ElMessageBox.prompt('变更原因', '变更原因', { inputPattern: /\S+/, inputErrorMessage: '必须填写原因' }); await run(() => api.replaceOperatorRoles(item, result.value.split(',').map((id) => Number(id.trim())), reason.value), '角色分配已更新'); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
async function transitionOperator(item: Operator, action: 'activate' | 'suspend' | 'close') { try { const reason = await ElMessageBox.prompt('变更原因', `${action} ${item.display_name}`, { inputPattern: /\S+/, inputErrorMessage: '必须填写原因' }); await run(() => api.transitionOperator(action, item, reason.value), '操作员状态已更新'); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
async function createRole() { await run(async () => { await api.createRole({ ...roleForm }); Object.assign(roleForm, { key: '', name: '', description: '' }); }, '平台角色已创建'); }
async function editRole(item: PlatformRole) { try { const name = await ElMessageBox.prompt('角色名称', `编辑 ${item.key}`, { inputValue: item.name, inputPattern: /\S+/, inputErrorMessage: '必须填写名称' }); const description = await ElMessageBox.prompt('说明', '角色说明', { inputValue: item.description || '' }); const reason = await ElMessageBox.prompt('变更原因', '变更原因', { inputPattern: /\S+/, inputErrorMessage: '必须填写原因' }); await run(() => api.updateRole(item, name.value, description.value, reason.value), '平台角色已更新'); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
function editPermissions(item: PlatformRole) { permissionRole.value = item; permissionSelection.value = [...item.permission_keys]; }
async function savePermissions() { if (!permissionRole.value) return; try { const reason = await ElMessageBox.prompt('变更原因', `保存 ${permissionRole.value.name} 的权限`, { inputPattern: /\S+/, inputErrorMessage: '必须填写原因' }); await run(() => api.replaceRolePermissions(permissionRole.value!, permissionSelection.value, reason.value), '角色权限已更新'); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
async function archiveRole(item: PlatformRole) { try { await ElMessageBox.confirm(`归档 ${item.name}？`, '确认归档', { type: 'warning' }); const reason = await ElMessageBox.prompt('变更原因', '变更原因', { inputPattern: /\S+/, inputErrorMessage: '必须填写原因' }); await run(() => api.archiveRole(item, reason.value), '平台角色已归档'); } catch (cause) { if (cause !== 'cancel' && cause !== 'close') error.value = message(cause); } }
onMounted(async () => { if (invitationToken.value) await inspectInvitation(); else if (authenticated.value) await loadView(); });
</script>
