<template>
  <section v-if="!authenticated" class="login-shell"><el-card class="login-card"><p class="brand">PEANUT ADMIN</p><h1>实例运营平台</h1><p class="muted">PlatformOperator 与 Tenant 管理员身份隔离。</p><el-form @submit.prevent="login"><el-form-item><el-input v-model="credentials.email" placeholder="平台账号邮箱" /></el-form-item><el-form-item><el-input v-model="credentials.password" type="password" show-password placeholder="密码" /></el-form-item><el-alert v-if="error" :title="error" type="error" :closable="false" /><el-button native-type="submit" type="primary" :loading="loading" class="wide">登录平台</el-button></el-form></el-card></section>
  <el-container v-else class="app-shell"><el-aside width="224px"><div class="logo">PEANUT <b>PLATFORM</b></div><el-menu :default-active="view" @select="view = $event"><el-menu-item index="overview">概览</el-menu-item><el-menu-item index="tenants">Tenant 与生命周期</el-menu-item><el-menu-item index="owners">Owner 邀请</el-menu-item><el-menu-item index="endpoints">入口域名与客户端</el-menu-item><el-menu-item index="modules">Module 目录</el-menu-item><el-menu-item index="operators">PlatformOperator</el-menu-item><el-menu-item index="roles">平台角色与权限</el-menu-item><el-menu-item index="audit">平台审计</el-menu-item></el-menu></el-aside><el-container><el-header><div><b>{{ title }}</b><span class="muted">实例控制面</span></div><el-button text @click="logout">退出登录</el-button></el-header><el-main><el-alert v-if="error" :title="error" type="error" show-icon @close="error = ''" />
    <template v-if="view === 'overview'"><div class="metric-grid"><el-card><span>Tenant 总数</span><strong>{{ tenants.length }}</strong></el-card><el-card><span>运行中 Tenant</span><strong>{{ activeCount }}</strong></el-card><el-card><span>已登记 Module</span><strong>--</strong><small>目录接口待接入</small></el-card><el-card><span>待处理邀请</span><strong>--</strong><small>邀请接口待接入</small></el-card></div><el-card><template #header>实例状态</template><el-descriptions :column="2"><el-descriptions-item label="控制面">PlatformOperator 独立会话</el-descriptions-item><el-descriptions-item label="Schema">当前 API 的 Tenant 生命周期已接入</el-descriptions-item><el-descriptions-item label="未知接口">以明确失败态显示，不回退到 Tenant 管理端</el-descriptions-item></el-descriptions></el-card></template>
    <template v-else-if="view === 'tenants'"><div class="toolbar"><el-button type="primary" @click="provisionDialog = true">新建 Tenant</el-button><el-button @click="loadTenants">刷新</el-button></div><el-table v-loading="loading" :data="tenants" row-key="id"><el-table-column prop="code" label="Tenant 编码" /><el-table-column prop="display_name" label="名称" /><el-table-column prop="status" label="状态"><template #default="{ row }"><el-tag :type="row.status === 'active' ? 'success' : row.status === 'suspended' ? 'warning' : 'info'">{{ row.status }}</el-tag></template></el-table-column><el-table-column prop="revision" label="版本" width="90" /><el-table-column label="操作" width="300"><template #default="{ row }"><el-button link type="primary" @click="detail(row)">详情</el-button><el-button v-if="row.status !== 'active' && row.status !== 'closed'" link type="success" @click="change(row, 'activate')">启用</el-button><el-button v-if="row.status === 'active'" link type="warning" @click="change(row, 'suspend')">暂停</el-button><el-button v-if="row.status !== 'closed'" link type="danger" @click="change(row, 'close')">关闭</el-button></template></el-table-column></el-table></template>
    <template v-else><el-card><template #header>{{ title }}</template><el-empty :description="`${title}接口尚未由后端提供`"><el-button @click="showUnavailable(title)">查看接口状态</el-button></el-empty></el-card></template>
  </el-main></el-container></el-container>
  <el-dialog v-model="provisionDialog" title="新建 Tenant" width="520px"><el-form label-position="top"><el-form-item label="Tenant 编码"><el-input v-model="provision.tenant_code" /></el-form-item><el-form-item label="Tenant 名称"><el-input v-model="provision.tenant_name" /></el-form-item><el-form-item label="Owner 邮箱"><el-input v-model="provision.owner_email" /></el-form-item><el-form-item label="Owner 显示名"><el-input v-model="provision.owner_display_name" /></el-form-item><el-form-item label="初始密码"><el-input v-model="provision.initial_password" type="password" show-password /></el-form-item></el-form><template #footer><el-button @click="provisionDialog=false">取消</el-button><el-button type="primary" :loading="loading" @click="createTenant">创建</el-button></template></el-dialog>
</template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { ElMessageBox } from 'element-plus';
import { api, unavailable, type Tenant } from './api/platform';
const authenticated = ref(!!localStorage.getItem('peanut-platform-token')); const loading = ref(false); const error = ref(''); const view = ref('overview'); const tenants = ref<Tenant[]>([]); const provisionDialog = ref(false);
const credentials = reactive({ email: '', password: '' }); const provision = reactive({ tenant_code: '', tenant_name: '', owner_email: '', owner_display_name: '', initial_password: '' });
const labels: Record<string, string> = { overview: '概览', tenants: 'Tenant 与生命周期', owners: 'Owner 邀请管理', endpoints: '入口域名与客户端', modules: 'Module 目录与 Tenant 状态', operators: 'PlatformOperator', roles: 'PlatformRole 与权限', audit: '平台审计' }; const title = computed(() => labels[view.value]); const activeCount = computed(() => tenants.value.filter((tenant) => tenant.status === 'active').length);
async function loadTenants() { loading.value = true; error.value = ''; try { tenants.value = (await api.tenants()).lists; } catch (cause) { error.value = (cause as Error).message; } finally { loading.value = false; } }
async function login() { loading.value = true; error.value = ''; try { await api.login(credentials.email.trim(), credentials.password); authenticated.value = true; await loadTenants(); } catch (cause) { error.value = (cause as Error).message; } finally { credentials.password = ''; loading.value = false; } }
async function logout() { await api.logout(); authenticated.value = false; tenants.value = []; view.value = 'overview'; }
async function createTenant() { loading.value = true; try { await api.provision({ ...provision }); provisionDialog.value = false; await loadTenants(); } catch (cause) { error.value = (cause as Error).message; } finally { provision.initial_password = ''; loading.value = false; } }
async function change(tenant: Tenant, action: 'activate' | 'suspend' | 'close') { const result = await ElMessageBox.prompt(`请输入${action}原因`, `${action} ${tenant.display_name}`, { inputPattern: /\S+/, inputErrorMessage: '必须填写原因' }); try { await api.transition(action, tenant, result.value); await loadTenants(); } catch (cause) { error.value = (cause as Error).message; } }
function detail(tenant: Tenant) { ElMessageBox.alert(`Tenant ID：${tenant.id}<br>编码：${tenant.code}<br>状态：${tenant.status}<br>修订：${tenant.revision}`, `${tenant.display_name} 详情`, { dangerouslyUseHTMLString: true }); }
function showUnavailable(name: string) { try { unavailable(name); } catch (cause) { error.value = (cause as Error).message; } }
onMounted(() => { if (authenticated.value) void loadTenants(); });
</script>
