<?php
declare(strict_types=1);
namespace app\common\service\storage;
use PDO;

final readonly class StorageConfigurationService
{
    public function __construct(private StorageRepository $repo){}
    public static function fromDefaultConnection():self{return new self(StorageRepository::fromDefaultConnection());}
    public function snapshot():array{return ['accounts'=>$this->repo->accounts(),'spaces'=>$this->repo->spaces(),'routes'=>$this->repo->routes(),'purposes'=>['material.image','material.video','material.file','export.xlsx','export.csv']];}
    public function createAccount(array $v):int
    {$driver=$this->driver((string)($v['driver']??''));$credentials=$this->credentials($driver,(array)($v['credentials']??[]));$s=$this->repo->pdo()->prepare("INSERT INTO pa_storage_account(account_key,driver,name,credentials,status,created_at,updated_at) VALUES(:account_key,:driver,:name,:credentials,'active',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))");$s->execute(['account_key'=>$this->key((string)($v['account_key']??''),64),'driver'=>$driver,'name'=>$this->name((string)($v['name']??'')),'credentials'=>$driver==='local'?null:json_encode($credentials,JSON_THROW_ON_ERROR)]);return(int)$this->repo->pdo()->lastInsertId();}
    public function updateAccount(array $v):void
    {$id=$this->id($v['id']??0);$s=$this->repo->pdo()->prepare('SELECT driver,credentials FROM pa_storage_account WHERE id=:id');$s->execute(['id'=>$id]);$old=$s->fetch(PDO::FETCH_ASSOC);if(!$old)throw new \InvalidArgumentException('存储账号不存在');$c=(array)($v['credentials']??[]);$oldc=json_decode((string)$old['credentials'],true)?:[];if(($c['secret_key']??'')==='******')$c['secret_key']=$oldc['secret_key']??'';$driver=(string)$old['driver'];$s=$this->repo->pdo()->prepare('UPDATE pa_storage_account SET name=:name,credentials=:credentials,status=:status,updated_at=UTC_TIMESTAMP(3) WHERE id=:id');$s->execute(['id'=>$id,'name'=>$this->name((string)($v['name']??'')),'credentials'=>$driver==='local'?null:json_encode($this->credentials($driver,$c),JSON_THROW_ON_ERROR),'status'=>$this->status((string)($v['status']??'active'),['active','disabled'])]);}
    public function createSpace(array $v):int
    {$accountId=$this->id($v['account_id']??0);$s=$this->repo->pdo()->prepare('SELECT driver FROM pa_storage_account WHERE id=:id');$s->execute(['id'=>$accountId]);$driver=$s->fetchColumn();if(!$driver)throw new \InvalidArgumentException('存储账号不存在');$access=StorageAccess::assertType((string)($v['access_type']??''));$bucket=$this->nullable((string)($v['bucket']??''));$region=$this->nullable((string)($v['region']??''));$endpoint=$this->url((string)($v['endpoint']??''));$domain=$this->url((string)($v['access_domain']??''));$local=$this->nullable((string)($v['local_path']??''));if($driver==='local'){if($local!==($access==='public'?'public/storage':'private/storage')||$bucket!==null)throw new \InvalidArgumentException('本地目录与公开属性不匹配');}elseif($bucket===null||$local!==null||($driver==='qcloud'&&$region===null)||($driver==='aliyun'&&$endpoint===null)||(($driver==='qiniu'||$access==='public')&&$domain===null))throw new \InvalidArgumentException('云 Space 位置配置不完整');$s=$this->repo->pdo()->prepare("INSERT INTO pa_storage_space(space_key,account_id,name,access_type,bucket,region,endpoint,access_domain,local_path,status,created_at,updated_at) VALUES(:space_key,:account_id,:name,:access_type,:bucket,:region,:endpoint,:access_domain,:local_path,'active',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))");$s->execute(['space_key'=>$this->key((string)($v['space_key']??''),64),'account_id'=>$accountId,'name'=>$this->name((string)($v['name']??'')),'access_type'=>$access,'bucket'=>$bucket,'region'=>$region,'endpoint'=>$endpoint,'access_domain'=>$domain,'local_path'=>$local]);return(int)$this->repo->pdo()->lastInsertId();}
    public function updateSpace(array $v):void
    {$s=$this->repo->pdo()->prepare('UPDATE pa_storage_space SET name=:name,access_domain=:domain,status=:status,updated_at=UTC_TIMESTAMP(3) WHERE id=:id');$s->execute(['id'=>$this->id($v['id']??0),'name'=>$this->name((string)($v['name']??'')),'domain'=>$this->url((string)($v['access_domain']??'')),'status'=>$this->status((string)($v['status']??'active'),['active','read_only','disabled'])]);}
    public function setRoute(array $v):void
    {$key=$this->key((string)($v['route_key']??''),96);$access=StorageAccess::assertType((string)($v['access_type']??''));if(str_starts_with($key,'default.')){if($key!=='default.'.$access)throw new \InvalidArgumentException('默认路由属性不匹配');}elseif(StoragePurpose::accessType($key)!==$access)throw new \InvalidArgumentException('用途路由属性不匹配');$space=$this->id($v['space_id']??0);$s=$this->repo->pdo()->prepare("SELECT 1 FROM pa_storage_space WHERE id=:id AND access_type=:access AND status='active'");$s->execute(['id'=>$space,'access'=>$access]);if(!$s->fetchColumn())throw new \InvalidArgumentException('路由目标 Space 不可用');$s=$this->repo->pdo()->prepare('INSERT INTO pa_storage_route(route_key,access_type,space_id,updated_at) VALUES(:route_key,:access,:space,UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE access_type=VALUES(access_type),space_id=VALUES(space_id),updated_at=VALUES(updated_at)');$s->execute(['route_key'=>$key,'access'=>$access,'space'=>$space]);}
    private function credentials(string $driver,array $c):array{if($driver==='local')return[];$a=trim((string)($c['access_key']??''));$s=trim((string)($c['secret_key']??''));if($a===''||$s==='')throw new \InvalidArgumentException('云存储凭据不完整');return['access_key'=>$a,'secret_key'=>$s];}
    private function driver(string $v):string{if(!in_array($v,['local','qiniu','aliyun','qcloud'],true))throw new \InvalidArgumentException('存储驱动无效');return$v;}
    private function id(mixed $v):int{$id=(int)$v;if($id<1)throw new \InvalidArgumentException('ID 无效');return$id;}
    private function key(string $v,int $max):string{$v=trim($v);if(strlen($v)>$max||preg_match('/^[a-z][a-z0-9._-]{2,95}$/D',$v)!==1)throw new \InvalidArgumentException('标识格式无效');return$v;}
    private function name(string $v):string{$v=trim($v);if($v===''||mb_strlen($v)>128)throw new \InvalidArgumentException('名称无效');return$v;}
    private function nullable(string $v):?string{$v=trim($v);return$v===''?null:$v;}
    private function url(string $v):?string{$v=trim($v);if($v==='')return null;if(filter_var($v,FILTER_VALIDATE_URL)===false||!in_array(strtolower((string)parse_url($v,PHP_URL_SCHEME)),['http','https'],true))throw new \InvalidArgumentException('访问地址无效');return rtrim($v,'/');}
    private function status(string $v,array $allowed):string{if(!in_array($v,$allowed,true))throw new \InvalidArgumentException('状态无效');return$v;}
}
